### ISSUE TITLE
The output of non-latin characters is broken

### ISSUE THREAD

**Issue by orangecoloured** [spite/chrome-sketchtab#4]
For example having a string in Russian "Привет" gives "%u041F%u0440%u0438%u0432%u0435%u0442" in the Output window.

**Comment by spite** [comment]
Indeed. Should be fixed with https://github.com/spite/chrome-sketchtab/commit/8e2abac6ea01de507c641e906d0db1b7ef9aaf91. It will updated on v0.6 shortly.

Thanks for reporting!
