### ISSUE TITLE
Infinite loop crashes new tab but isn't cleared

### ISSUE THREAD

**Issue by gomako** [spite/chrome-sketchtab#6]
I was being dumb and caused an infinite loop which crashed the tab, because it is saved, every time I reopen the tab it crashes before I can get in and delete the offending code.

I deleted the extension and reinstalled it to fix it, but maybe have a start button when you first open the tab which then auto runs after that?

**Comment by spite** [comment]
Yes, it's happened to me a few times 😁
It should be fixed with https://github.com/spite/chrome-sketchtab/commit/18fab6d9f98768d0630f33b8817c837703e6b2dc and updated on 0.7 on the chrome store.

Thanks for reporting!
